[[profiles]]
name = "desktop"
synced_files = [
    ".abcde.conf",
    ".bash_logout",
    ".bashrc",
    ".config/alacritty/alacritty.yml",
    ".config/atuin/config.toml",
    ".config/bat/config",
    ".config/fish/config.fish",
    ".config/fzf/fzf_conf.fish",
    ".config/gh/config.yml",
    ".config/ghostty/config",
    ".config/helix/config.toml",
    ".config/helix/languages.toml",
    ".config/jj/config.toml",
    ".config/micro/bindings.json",
    ".config/micro/settings.json",
    ".config/navi/config.yaml",
    ".config/neofetch/config.conf",
    ".config/nushell/config.nu",
    ".config/nushell/env.nu",
    ".config/nushell/plugins.nu",
    ".config/nvim",
    ".config/pipewire/client.conf",
    ".config/pipewire/pipewire-pulse.conf",
    ".config/pipewire/pipewire.conf",
    ".config/starship.toml",
    ".config/yazi/wrapper.fish",
    ".config/yazi/yazi.toml",
    ".config/zellij",
    ".duckdbrc",
    ".gemrc",
    ".golangci.yml",
    ".nanorc",
    ".profile",
    ".tmux.conf",
    ".zshrc",
    "Justfile",
    "julia.nanorc",
    "make_symlinks.sh",
    "ruff.toml",
]
packages = []

[[profiles]]
name = "laptop"
synced_files = []
packages = []

[[profiles]]
name = "work"
synced_files = []
packages = []
