[general]
live_config_reload = true
import = [
	"~/.config/alacritty/themes/alacritty-theme/themes/catppuccin_macchiato.toml"
	]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Beam", blinking = "On"}

[font]
size = 12.0
builtin_box_drawing = true

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
#family = "MonaspaceArgon"
#family = "Martian Mono"
#family = "FreeMono"
family = "Mononoki Nerd Font"
style = "Regular"

[window]
decorations = "None"
dynamic_title = true

