# ~/.config/starship.toml

format = """ 
[┌────────────────>](bold green)$username$hostname$status 
[│](bold green)$directory$git_branch$git_status 
[└─](bold green)$character
""" 

[character] 
success_symbol = "[⟩](bold green)" 
error_symbol = "[!](bold red) " 
vicmd_symbol = "[V](bold green) " 

[conda] 
symbol="コ" 
format = "[$symbol$environment](dimmed green) " 

[python] 
symbol = "蛇 " 
python_binary = "python3" 
pyenv_version_name = true 

[username] 
style_user = "white bold" 
style_root = "black bold" 
format = "[$user]($style)" 
disabled = false 

[hostname] 
ssh_only = true 
format = "@[$hostname](bold red) " 
trim_at = ".companyname.com"
disabled = false

[directory] 
truncation_length = 10 
truncate_to_repo = false
style = "black bold dimmed"

[git_branch] 
symbol = "" 
style = "bold white" 
format = '[\($symbol$branch\)]($style) ' 

[git_status]
untracked = "" 
format = '([\[$conflicted$deleted$renamed$modified$staged$behind\]]($style) )' 
modified = '*' 

[status] 
disabled = false
format = '[\[$status - $common_meaning\]](green)'

