"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Ryan Hildebrandt"
email = "ryancahildebrandt@gmail.com"

[ui]
editor = "micro"
color = "auto"
default-command = ["log", "-n=5"]
pager = "delta"
diff-formatter = ":git"
