live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "0xe0def4"
text = "0x191724"

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[cursor]
style = "Beam"

[font]
size = 8.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Italic"

[font.normal]
#family = "MonaspaceArgon"
#family = "Martian Mono"
#family = "FreeMono"
family = "Mononoki Nerd Font"
style = "Regular"

[window]
decorations = "None"
